### ISSUE TITLE
Update PF icon imports to help with bundle size

### ISSUE THREAD

**Issue by SanjalKatiyar** [red-hat-storage/odf-console#1196]
Check: https://github.com/openshift/console/pull/12983/commits/e026b1562a04fc526f2ecf84269b1aaeb8e12f7c.
Needs a bit of investigation whether it is really needed or not.

**Comment by bipuladh** [comment]
This is mostly for PF5.

**Comment by SanjalKatiyar** [comment]
Closing this as it is not needed.
