### ISSUE TITLE
Fix "resource" object argument

### ISSUE THREAD

**Issue by SanjalKatiyar** [red-hat-storage/odf-console#205]
example: https://github.com/red-hat-storage/odf-console/blob/7baa58e24b964487ce31a3a76d6c357980d8ed60/packages/odf/components/resource-pages/list-page.tsx#L197

Key should be "namespace" not "ns" else useK8sWatchResource will return resources in every namespace.
Check for all such instances for useK8sWatchResource and fix at all places (if found at other places).

**Comment by SanjalKatiyar** [comment]
https://github.com/red-hat-storage/odf-console/pull/215

**Comment by bipuladh** [comment]
You have mentioned 215 but do we need to change this across other components too?

**Comment by SanjalKatiyar** [comment]
> You have mentioned 215 but do we need to change this across other components too?

I did take a look, other places looks good !
