### ISSUE TITLE
Some test attributes do not exist on ODF4.11

### ISSUE THREAD

**Issue by OdedViner** [red-hat-storage/odf-console#264]
OCP Version:
OCP Version: 4.11.0-0.nightly-2022-06-04-014713
ODF Version: 4.11.0-85

https://docs.google.com/document/d/1-yHsQwbf7aAGnxMr8Ycg0bJx2NPT3Z-60L2ZYS1b6sI/edit

**Comment by SanjalKatiyar** [comment]
Closing as PR mentioned above is merged.
