### ISSUE TITLE
Update copyright info in the license

### ISSUE THREAD

**Issue by SanjalKatiyar** [red-hat-storage/odf-console#374]
This: https://github.com/red-hat-storage/odf-console/blob/8268ff4b77a552b8336eeead1e62e99fbdc90863/LICENSE#L189 needs to be updated.

Reference: https://github.com/openshift/origin/blob/e6728e5e1d97886ba122ecca731716fc4d6e9ebf/LICENSE#L179

**Comment by TimothyAsirJeyasing** [comment]
https://github.com/red-hat-storage/odf-console/pull/610
