### ISSUE TITLE
Update ReadMe

### ISSUE THREAD

**Issue by SanjalKatiyar** [red-hat-storage/odf-console#546]
Need to add steps on how to perform (locally):

- end-to-end testing.

- unit testing.

**Comment by SanjalKatiyar** [comment]
reference:
https://github.com/openshift/console#unit-tests
https://github.com/openshift/console#integration-tests

**Comment by TimothyAsirJeyasing** [comment]
https://github.com/red-hat-storage/odf-console/pull/568
