### ISSUE TITLE
Move "i18n-scripts" under "scripts"

### ISSUE THREAD

**Issue by SanjalKatiyar** [red-hat-storage/odf-console#551]
there are 2 different directories: `i18n-scripts` & `scripts`
structure should be:

> scripts
>> generatePluginPackage.ts
>> i18n

**Comment by SanjalKatiyar** [comment]
reference:
https://github.com/openshift/console#unit-tests
https://github.com/openshift/console#integration-tests

**Comment by TimothyAsirJeyasing** [comment]
https://github.com/red-hat-storage/odf-console/pull/562

**Comment by TimothyAsirJeyasing** [comment]
https://github.com/red-hat-storage/odf-console/pull/562 merged
