### ISSUE TITLE
[bug] [odf/mco] Fix anti-pattern in SelectorInput

### ISSUE THREAD

**Issue by SanjalKatiyar** [red-hat-storage/odf-console#671]
SelectorInput (https://github.com/red-hat-storage/odf-console/blob/master/packages/shared/modals/Selector.tsx#L173): used in add labels modal and apply-policy (mco) modal.

Priority of issue is "low" **for now**, still it is an anti-pattern and may cause bug moving forward if this component is used at multiple places.
Check demo: https://codesandbox.io/s/m3w9zn1z8x (same case can happen with SelectorInput as well)
Refer: https://reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html#common-bugs-when-using-derived-state

**Comment by SanjalKatiyar** [comment]
cc @bipuladh @GowthamShanmugam (just FYI)

**Comment by SanjalKatiyar** [comment]
commit which introduced this: https://github.com/red-hat-storage/odf-console/pull/579/commits/299a8796b77f9bb833d4346b056fcfad0fcffe84#diff-c6f3325fae0fffcf0cf61edd0c338cd51f59a881106d9000842c4370b6990c5c

**Comment by TimothyAsirJeyasing** [comment]
Shall we replace getDerivedStateFromProps with componentDidUpdate similar to console repo for SelectorInput ?
