### ISSUE TITLE
Add validation for before setting odf flag

### ISSUE THREAD

**Issue by TimothyAsirJeyasing** [red-hat-storage/odf-console#764]
Currently we are setting this setODFflag to true however we improve here by setting the value after checking for the class definition or custom resource definition found or not.

**Comment by SanjalKatiyar** [comment]
better to remove this flag IMO, there is no need for it anymore @bipuladh wdyt ??

**Comment by SanjalKatiyar** [comment]
not required as flag is only added when ODF is installed and odf-console starts to run.
